#!/usr/bin/env bash
set -euxo pipefail

function getRelative {
    echo $(realpath -- "$(dirname -- "${BASH_SOURCE[0]}")/$1")
}

function realizeTemplate {
    TEMPLATE_PATH="$(getRelative "${1}-template.${2}")"
    REALIZED_PATH="$(getRelative "${1}.${2}")"
    HOST="$(hostname)"

    cp --remove-destination ${TEMPLATE_PATH} ${REALIZED_PATH}
    sd -F "MISSING" ${HOST} ${REALIZED_PATH}
}

host="$(echo $HOSTNAME)" #$(hostname)

~bzm3r/system/system/realize-template ~bzm3r/system/system/min-iso/specific-scripts nix

~bzm3r/system/system/realize-template ~bzm3r/system/system/min-iso/gen-iso sh

# nix-instantiate --eval has no raw mode yet
nixpkgsPath=$(nix-instantiate --eval --read-write-mode ~bzm3r/system/system/nixpkgs/path.nix | tr -d \")

NIX_PATH=nixpkgs=$nixpkgsPath ./min-iso/gen-iso.sh
./min-iso/burn-iso.sh ${1}
