#!/usr/bin/env bash
set -euo pipefail

scriptDir=$(dirname -- "${BASH_SOURCE[0]}")

$scriptDir/set-env

read -p "Generation label? " label

# test -z STRING: test if STRING has zero length
# (test -n STRING for non-zero length test)
if test -z "$label"; then
    echo "No label provided."
else
    NIXOS_LABEL=${label}
    export NIXOS_LABEL
fi
exec nixos-rebuild "$@"
