#!/usr/bin/env bash
set -euo pipefail

echo "Executing rebuild..."

nixosConf=~bzm3r/nixos-conf

configTemplate=${nixosConf}/nixos/configuration
${nixosConf}/realize-template $configTemplate "nix"

nixpkgsPath=${nixosConf}/nixpkgs/path.nix
# nix-instantiate --eval has no raw mode yet
nixpkgsPath=$(nix-instantiate --eval --read-write-mode $nixpkgsPath | tr -d \")
# Get the ./root.nix relative to this script
configPath=$(realpath -- "$(dirname -- "${BASH_SOURCE[0]}")/root.nix")

# nixos-rebuild always reads Nixpkgs from the NIX_PATH,
# so we need to set it explicitly to our pinned version
NIX_PATH=nixpkgs=$nixpkgsPath:nixos-config=$configPath
export NIX_PATH