#!/usr/bin/env bash
set -euxo pipefail

function getRelative {
    echo $(realpath -- "$(dirname -- "${BASH_SOURCE[0]}")/$1")
}

function realizeTemplate {
    TEMPLATE_PATH="$(getRelative "${1}-template.${2}")"
    REALIZED_PATH="$(getRelative "${1}.${2}")"
    HOST="$(hostname)"

    cp --remove-destination ${TEMPLATE_PATH} ${REALIZED_PATH}
    sd -F "MISSING" ${HOST} ${REALIZED_PATH}
}
