#!/usr/bin/env bash
set -euo pipefail

function realize_template {
cp --remove-destination ~bzm3r/nixos-conf/nixos/$1-template.nix ~bzm3r/nixos-conf/nixos/$1.nix
sd -F 'MISSING' $host ~bzm3r/nixos-conf/nixos/configuration.nix
}

trap cleanup EXIT

host="$(echo $HOSTNAME)" #$(hostname)
echo "Executing rebuild..."
# nix-instantiate --eval has no raw mode yet
nixpkgsPath=$(nix-instantiate --eval --read-write-mode ~bzm3r/nixos-conf/nixpkgs/path.nix | tr -d \")
# Get the ./root.nix relative to this script
configPath=$(realpath -- "$(dirname -- "${BASH_SOURCE[0]}")/root.nix")

cp --remove-destination ~bzm3r/nixos-conf/nixos/configuration-template.nix ~bzm3r/nixos-conf/nixos/configuration.nix
sd -F 'MISSING' $host ~bzm3r/nixos-conf/nixos/configuration.nix
# nixos-rebuild always reads Nixpkgs from the NIX_PATH,
# so we need to set it explicitly to our pinned version
NIX_PATH=nixpkgs=$nixpkgsPath:nixos-config=$configPath
export NIX_PATH

exec nixos-rebuild "$@"

cleanup

./iso-scripts/gen-iso-$1
./iso-scripts/burn-iso $1 $2
