#!/bin/sh
echo "Available Network Interfaces:"
ip link

systemctl start wpa_supplicant

echo "Network name?"
read net_name

echo "Network pass?"
read net_pass

wpa_cli add_network
wpa_cli set_network 0 ssid '"'$net_name'"'
wpa_cli set_network 0 psk '"'$net_pass'"'
wpa_cli set_network 0 key_mgmt WPA-PSK
wpa_cli enable_network 0

sleep 1
